version: "3.9"
services:
  web:
    build: .
    entrypoint: "/bin/sh -c 'npm install && npm run dev'"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    depends_on:
      - nginx

  nginx:
    image: nginx
    volumes:
      - ./sheets/:/var/www/sheets/
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    command: [nginx-debug, '-g', 'daemon off;']